// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLi_u65biqevlo216SIcjSNXGglPtCMqs',
    appId: '1:151879993363:web:80b97fb7b046346bd0d7e6',
    messagingSenderId: '151879993363',
    projectId: 'applifebalance',
    authDomain: 'applifebalance.firebaseapp.com',
    storageBucket: 'applifebalance.firebasestorage.app',
    measurementId: 'G-T9N329T6ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoW_D67ED_roX77QQHAy_MnI6YJpQMCEs',
    appId: '1:151879993363:android:6bd57009331a2415d0d7e6',
    messagingSenderId: '151879993363',
    projectId: 'applifebalance',
    storageBucket: 'applifebalance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVxxTf9fVioO9eCe2ovcZnnOWDWJ0kFo',
    appId: '1:151879993363:ios:f336bf8899086f13d0d7e6',
    messagingSenderId: '151879993363',
    projectId: 'applifebalance',
    storageBucket: 'applifebalance.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeVxxTf9fVioO9eCe2ovcZnnOWDWJ0kFo',
    appId: '1:151879993363:ios:f336bf8899086f13d0d7e6',
    messagingSenderId: '151879993363',
    projectId: 'applifebalance',
    storageBucket: 'applifebalance.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLi_u65biqevlo216SIcjSNXGglPtCMqs',
    appId: '1:151879993363:web:5ae658955b21625bd0d7e6',
    messagingSenderId: '151879993363',
    projectId: 'applifebalance',
    authDomain: 'applifebalance.firebaseapp.com',
    storageBucket: 'applifebalance.firebasestorage.app',
    measurementId: 'G-FE8X5SREFW',
  );
}
